name: plugin-ci

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: plugin-ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    uses: ./.github/workflows/plugin-ci-core.yml
    permissions:
      contents: read
